cooldown-seconds: 60
maximum-checks: 100

enabled-worlds:
    world:
        radius: 20000
        centre:
            x: 0
            z: 0
    world_the_end:
        radius: 20000
        centre:
            x: 0
            z: 0
