name: RTP
author: David Hickey
description: Teleports players to a random location in the wilderness.
version: maven-version-number

main: davidhickey.bukkit_rtp.RTPPlugin

commands:
    rtp:
        description: All commands for RTP
        usage: /rtp <subcommand> [args]
        permission: rtp.rtp
        aliases: [rtele, rteleport, randtp, randtele, randteleport, randomtp, randomtele, randomteleport]

permissions:
    rtp.rtp:
        default: true
        description: Anyone without this permission can't use /rtp AT ALL

    rtp.tp:
        default: true
        description: Allow /rtp tp

    rtp.tp.radius:
        default: op
        description: Allow /rtp tp [radius]

    rtp.config:
        default: op
        description: Allow /rtp config

    rtp.tp.nocooldown:
        default: op
        description: Allows you to bypass the cooldown

    rtp.reload:
        default: op
        description: Allows /rtp reload
